name: Build ESP32 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run

      - name: Build SPIFFS (html/png)
        run: platformio run --target buildfs

      - name: Check output files
        run: ls -l .pio/build/esp32s3

      - name: Upload firmware and spiffs
        uses: actions/upload-artifact@v4
        with:
          name: esp32-artifacts
          path: |
            .pio/build/esp32s3/firmware.bin
            .pio/build/esp32s3/spiffs.bin
