name: Build ESP32 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          # `cache: 'pip'` ni olib tashladik, chunki maxsus qadoqlash kerak emas
          # Agar kerak bo'lsa, PlatformIO uchun maxsus talabni qo'shish mumkin

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run

      - name: Build SPIFFS (html/png)
        run: platformio run --target buildfs

      - name: Check output files
        run: |
          ls -l .pio/build/esp32s3/firmware.bin
          ls -l .pio/build/esp32s3/spiffs.bin
          ls -l .pio/build/esp32s3/bootloader.bin
          ls -l .pio/build/esp32s3/partitions.bin

      - name: Check build status
        run: |
          if [ -f .pio/build/esp32s3/firmware.bin ]; then
            echo "Build muvaffaqiyatli!"
          else
            echo "XATO: Build muvaffaqiyatsiz!"
            exit 1
          fi

      - name: Upload firmware, spiffs, bootloader, and partitions
        uses: actions/upload-artifact@v4
        with:
          name: esp32-artifacts
          path: |
            .pio/build/esp32s3/firmware.bin
            .pio/build/esp32s3/spiffs.bin
            .pio/build/esp32s3/bootloader.bin
            .pio/build/esp32s3/partitions.bin
